-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Apr 09, 2026 at 02:28 PM
-- Server version: 10.6.25-MariaDB
-- PHP Version: 8.4.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `amazonf1_amazon_filtration`
--

-- --------------------------------------------------------
 
--
-- Table structure for table `products`
--

CREATE TABLE `products` ( 
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `code` varchar(100) NOT NULL,
  `category` varchar(100) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `description` text DEFAULT NULL,
  `image` varchar(500) DEFAULT NULL,
  `specifications` text DEFAULT NULL,
  `applications` text DEFAULT NULL,
  `status` enum('Active','Inactive','Discontinued') DEFAULT 'Active',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `code`, `category`, `price`, `description`, `image`, `specifications`, `applications`, `status`, `created_at`, `updated_at`) VALUES
(25, 'Air Filter', 'E297L', 'Air Filters', 5500.00, 'The E297L Original Air Filter is a high-performance filter designed to deliver superior air purification and engine protection. Built with precision and quality materials, it effectively traps dust, dirt, and other airborne contaminants before they enter the engine, ensuring optimal performance and longer engine life.', 'uploads/68ea2f1fbf5dd_1760177951.png', 'Type: Engine Air Filter\r\nModel Code: E297L\r\nShape: Rectangular\r\nFilter Material: Multi-layered synthetic fiber\r\nOuter Frame: Durable rubber/plastic seal\r\nCompatibility: Direct replacement for original OEM filters\r\nQuality Standard: OEM equivalent / ISO certified', 'Specifically used for MP1 Benz Trucks (Mercedes-Benz Actros / Axor MP1 series).\r\nSuitable for heavy-duty use and long service intervals.', 'Active', '2025-10-11 10:19:11', '2025-10-21 12:25:43'),
(26, 'Air Filter', '17801-70050', 'Air Filters', 250.00, 'The 17801-70050 Air Filter is a premium-quality replacement filter designed to maintain clean airflow into your vehicle’s engine. It efficiently captures dust, pollen, and other airborne contaminants, helping your engine run smoothly and improving overall performance and fuel efficiency.', 'uploads/68ea32662ddda_1760178790.png', 'Type: Engine Air Filter\r\nModel Code: 17801-70050\r\nMaterial: High-efficiency paper filter element with durable sealing rubber\r\nShape: Rectangular / panel type\r\nQuality: OEM-standard replacement filter\r\nFiltration Efficiency: ?99% for fine particles\r\nInstallation: Direct fit—no modification required', 'Compatible Vehicles:\r\nToyota Altezza / Altezza Gita\r\nToyota Chaser\r\nToyota Cresta\r\nToyota Crown Comfort\r\nToyota Crown/Majesta\r\nToyota Lexus (select models)', 'Active', '2025-10-11 10:33:10', '2025-10-21 12:29:23'),
(27, 'Air Filter', '17801-21030', 'Air Filters', 170.00, 'The 17801-21030 Air Filter is a high-quality replacement filter designed to protect your engine by providing clean, efficient airflow. It effectively captures dust, dirt, and debris from the incoming air, ensuring optimal combustion, improved fuel efficiency, and prolonged engine life.', 'uploads/68ea979355a8d_1760204691.png', 'Type: Engine Air Filter\r\nModel Code: 17801-21030\r\nFilter Media: Multi-layered high-efficiency paper element\r\nFrame Material: Durable rubber sealing edge\r\nShape: Panel-type filter\r\nFiltration Efficiency: ?99% particle capture rate\r\nQuality: OEM-equivalent replacement\r\nInstallation: Direct fit—no modification required', 'Compatible Vehicle Models:\r\nToyota bB\r\nToyota Corolla / Axio / Fielder\r\nToyota Echo', 'Active', '2025-10-11 11:24:00', '2025-10-21 12:31:57'),
(28, 'Air Filter', '17801-23030', 'Air Filters', 170.00, 'The 17801-23030 Air Filter is an OEM-quality replacement filter designed to provide maximum engine protection and performance. It effectively traps dust, dirt, and debris to ensure clean airflow into the engine, enhancing fuel efficiency and reducing engine wear.', 'uploads/68ea97ad2c0de_1760204717.png', 'Type: Engine Air Filter\r\nModel Code: 17801-23030\r\nFilter Media: Multi-layered, high-efficiency paper element\r\nFrame Material: Durable rubber sealing edge for a tight fit\r\nShape: Panel-type filter\r\nFiltration Efficiency: ?99% particle capture rate\r\nQuality: OEM-equivalent performance\r\nInstallation: Direct fit—no modification required', 'Compatible Vehicle Models:\r\nToyota Aygo\r\nToyota bB\r\nToyota Passo\r\nToyota Platz\r\nToyota Ractis', 'Active', '2025-10-11 11:24:59', '2025-10-21 12:35:17'),
(29, 'Air Filter', '17801-22020', 'Air Filters', 170.00, 'The 17801-22020 Air Filter is a high-performance OEM-quality replacement filter designed to maintain clean airflow into your engine. It effectively traps dust, debris, and airborne particles, ensuring smooth engine operation, better fuel efficiency, and extended engine life.', 'uploads/68ea97c615e30_1760204742.png', 'Type: Engine Air Filter\r\nModel Code: 17801-22020\r\nFilter Media: High-efficiency pleated paper element\r\nFrame Material: Reinforced rubber sealing edge\r\nShape: Rectangular panel filter\r\nFiltration Efficiency: ?99% dust and particle capture\r\nCompatibility: OEM-standard size and fit\r\nInstallation: Easy, direct-fit replacement', 'Compatible Vehicle Models:\r\nToyota Avensis\r\nToyota Caldina\r\nToyota Corolla ', 'Active', '2025-10-11 11:28:48', '2025-10-21 12:45:49'),
(30, 'Air Filter', '17801-21050', 'Air Filters', 180.00, 'The 17801-21050 Air Filter is a high-quality replacement filter engineered to provide clean and efficient airflow to your vehicle’s engine. It effectively removes dust, dirt, and other airborne contaminants, ensuring maximum engine performance, better fuel economy, and longer engine life.', 'uploads/68eb331c8ab9f_1760244508.png', 'Type: Engine Air Filter\r\nModel Code: 17801-21050\r\nFilter Media: Multi-layer pleated paper for superior filtration\r\nFrame Material: High-durability rubber sealing edge\r\nShape: Panel-type air filter\r\nFiltration Efficiency: ?99% dust particle removal\r\nQuality: OEM-equivalent performance\r\nInstallation: Direct-fit replacement—no modification needed', 'Compatible Vehicle Models:\r\nToyota Auris/Corolla\r\nToyota Belta\r\nToyota Corolla\r\nToyota Corolla Altis\r\nToyota Corolla Axio / Fielder', 'Active', '2025-10-11 11:29:44', '2025-10-21 12:48:10'),
(31, 'Air Filter', '17801-50060', 'Air Filters', 200.00, 'The 17801-50060 Air Filter is a premium-quality replacement filter designed to deliver superior engine protection and airflow. It efficiently captures dust, dirt, and debris, ensuring your vehicle’s engine runs smoothly and efficiently. Built with durable materials, it maintains filtration performance over an extended service life, promoting fuel efficiency and reducing engine wear.', 'uploads/68ea97ebae44e_1760204779.png', 'Type: Engine Air Filter\r\nModel Code: 17801-50060\r\nFilter Media: High-efficiency pleated paper element\r\nFrame Material: Reinforced rubber sealing edge\r\nShape: Rectangular panel filter\r\nFiltration Efficiency: ?99% dust particle retention\r\nCompatibility: OEM-quality fit and performance\r\nInstallation: Simple, direct-fit replacement—no modifications required', 'Compatible Vehicle Models:\r\nToyota Crown/Majesta\r\nToyota Lexus GS\r\nToyota Lexus SC\r\nToyota Soarer', 'Active', '2025-10-11 11:30:41', '2025-10-21 12:50:53'),
(32, 'Air Filter', '17801-26020', 'Air Filters', 450.00, 'The 17801-26020 Air Filter is a high-efficiency OEM-quality filter designed to deliver superior filtration performance and engine protection. It effectively traps dust, dirt, and other airborne particles to ensure clean airflow into the engine, promoting smoother performance, better fuel efficiency, and longer engine life.', 'uploads/68ea9801188a9_1760204801.png', 'Type: Engine Air Filter\r\nModel Code: 17801-26020\r\nFilter Media: Multi-layer pleated paper for enhanced filtration\r\nFrame Material: Durable rubber sealing edge for a secure fit\r\nShape: Panel-type air filter\r\nFiltration Efficiency: ?99% dust and particle removal\r\nQuality: OEM-standard replacement\r\nInstallation: Direct-fit — easy to install, no modification required', 'Compatible Vehicle Models:\r\nToyota Altis\r\nToyota Verso\r\nToyota Camry\r\nToyota RAV4', 'Active', '2025-10-11 11:31:29', '2025-10-21 12:54:07'),
(33, 'Air Filter', 'E272L', 'Air Filters', 4000.00, 'The E272L Air Filter is a premium-grade engine air filter designed for exceptional durability and efficiency. It provides maximum filtration performance by capturing dust, dirt, and contaminants, ensuring clean airflow into the engine. This helps improve combustion efficiency, reduce wear, and extend overall engine life — ideal for heavy-duty vehicles and trucks.', 'uploads/68eb333ae9cf2_1760244538.png', 'Type: Engine Air Filter\r\nModel Code: E272L\r\nFilter Media: Multi-layer high-density pleated paper element\r\nFrame Material: Heavy-duty rubber sealing edge\r\nShape: Cylindrical / round type (depending on vehicle model)\r\nFiltration Efficiency: ?99% dust and particle retention\r\nBuild Quality: OEM-equivalent heavy-duty construction\r\nInstallation: Direct-fit replacement, no modification required', 'Compatible Vehicle Models:\r\nMercedes-Benz MP2\r\nMercedes-Benz MP3\r\n', 'Active', '2025-10-11 11:31:32', '2025-10-21 12:57:34'),
(34, 'Air Filter', '17801-26010', 'Air Filters', 600.00, 'Air Filter', 'uploads/68ea98274a542_1760204839.png', '', 'LEXUS II, RAV4 III 2015 MODELS', 'Active', '2025-10-11 11:32:22', '2025-10-11 17:47:19'),
(35, 'Air Filter', '17801-20050', 'Air Filters', 350.00, 'The 17801-20050 Air Filter is a high-quality replacement filter built to deliver efficient airflow and superior engine protection. It effectively captures dust, dirt, and other airborne contaminants to ensure your engine runs smoothly, maintains optimal performance, and achieves better fuel efficiency.', 'uploads/68ea96f71a982_1760204535.png', 'Type: Engine Air Filter\r\nModel Code: 17801-20050\r\nFilter Media: High-efficiency pleated paper element\r\nFrame Material: Durable rubber sealing edge\r\nShape: Panel-type filter\r\nFiltration Efficiency: ?99% dust and particle retention\r\nQuality: OEM-standard replacement part\r\nInstallation: Direct-fit—easy to install, no modification required', 'Compatible Vehicle Models:\r\nToyota Alphard (Old Model\r\nToyota TownAce', 'Active', '2025-10-11 11:33:11', '2025-10-21 13:01:18'),
(36, 'Air Filter', 'MR968274', 'Air Filters', 350.00, 'The MR968274 Air Filter is an OEM-quality replacement filter designed to deliver reliable engine protection and consistent performance. It effectively traps dust, dirt, and debris from the air intake system, ensuring clean airflow for improved combustion efficiency, fuel economy, and engine longev', 'uploads/68ea970b78bb9_1760204555.png', 'Type: Engine Air Filter\r\nModel Code: MR968274\r\nFilter Media: Multi-layer high-efficiency pleated paper element\r\nFrame Material: Heavy-duty rubber sealing edge for secure fit\r\nShape: Panel-type filter\r\nFiltration Efficiency: ?99% dust and particle capture\r\nQuality: OEM-equivalent performance and durability\r\nInstallation: Direct-fit replacement—easy and quick to install', 'Compatible Vehicle Models:\r\nMitsubishi Outlander\r\nMitsubishi Galant\r\nMitsubishi Pajero\r\nMitsubishi Lancer (New Models)', 'Active', '2025-10-11 11:34:13', '2025-10-21 13:04:03'),
(37, 'AIR FILTER', 'E497L', 'Air Filters', 5500.00, 'The E497L Air Filter is a heavy-duty, high-efficiency filter designed to provide maximum engine protection for commercial and industrial vehicles. It effectively removes dust, dirt, and contaminants from the air intake system, ensuring optimal airflow and combustion efficiency. Built with premium materials, this filter guarantees durability and long service life — ideal for high-performance engines like the Mercedes-Benz Actros.', 'uploads/68eb33b416f60_1760244660.png', 'Type: Engine Air Filter\r\nModel Code: E497L\r\nFilter Media: Multi-layer, high-efficiency pleated paper element\r\nFrame Material: Heavy-duty rubber sealing edge\r\nShape: Cylindrical filter\r\nFiltration Efficiency: ?99% dust and particle retention\r\nQuality: OEM-grade heavy-duty replacement\r\nInstallation: Direct-fit—no modification required', 'Compatible Vehicle Model:\r\nMercedes-Benz Actros', 'Active', '2025-10-11 11:34:24', '2025-10-21 13:08:08'),
(38, 'Air Filter', '17801-20040', 'Air Filters', 200.00, 'The 17801-20040 Air Filter is a premium-quality replacement filter designed to maintain your engine’s performance and efficiency. It provides superior protection by trapping dust, dirt, and debris from the air intake system, ensuring clean airflow for better combustion, fuel economy, and reduced engine wear.', 'uploads/68ea9730740e9_1760204592.png', 'Type: Engine Air Filter\r\nModel Code: 17801-20040\r\nFilter Media: High-efficiency pleated paper element\r\nFrame Material: Durable rubber sealing edge\r\nShape: Rectangular / panel type\r\nFiltration Efficiency: ?99% dust and particle capture\r\nQuality: OEM-standard replacement\r\nInstallation: Direct-fit—easy installation with no modification required', 'Compatible Vehicle Model:\r\nToyota Harrier', 'Active', '2025-10-11 11:34:59', '2025-10-21 13:15:54'),
(39, 'Air Filter', '17801-31120', 'Air Filters', 250.00, 'The Air Filter 17801-31120 is a high-quality replacement filter designed to deliver clean airflow to your engine for maximum performance and longevity. It effectively captures dust, dirt, and debris, ensuring smooth engine operation, improved fuel efficiency, and lower emissions. Built to OEM standards, this filter guarantees a perfect fit and reliable performance for your vehicle.', 'uploads/68ea9746758cf_1760204614.png', 'Type: Engine Air Filter\r\nModel Code: 17801-31120\r\nMaterial: Multi-layer high-efficiency filter paper\r\nFrame: Sealed rubber edge for tight fit\r\nFiltration Efficiency: ?99% for dust and airborne particles\r\nInstallation: Direct replacement—no modification required\r\nQuality Standard: OEM Equivalent', 'Compatible with the following models:\r\nToyota RAV4 (New Model)\r\nToyota Estima\r\nToyota Mark X\r\nToyota Alphard (New Model)', 'Active', '2025-10-11 11:35:52', '2025-10-21 13:18:33'),
(40, 'Air Filter', 'E603L', 'Air Filters', 4000.00, 'The Air Filter E603L is a premium-quality replacement air filter designed for Mercedes-Benz MP2 and MP3 trucks. It provides exceptional filtration efficiency, protecting your engine from harmful dust, dirt, and debris while maintaining optimal airflow for powerful performance. Built to OEM standards, this filter ensures reliability, durability, and a perfect fit.\r\n', 'uploads/68eb3e55f2a1f_1760247381.jpeg', 'Type: Heavy-Duty Engine Air Filter\r\nModel Code: E603L\r\nMaterial: High-efficiency pleated paper element\r\nFrame: Reinforced rubber sealing for tight, leak-free fit\r\nFiltration Efficiency: ?99% particle capture rate\r\nApplication Class: Commercial truck / long-haul use\r\nInstallation: Direct fit—no modification required\r\nStandard: OEM Equivalent / ISO Certified', 'Compatible with:\r\nMercedes-Benz Actros MP2\r\nMercedes-Benz Actros MP3', 'Active', '2025-10-11 11:36:38', '2025-10-21 13:20:17'),
(41, 'Air Filter', '17801-28010', 'Air Filters', 200.00, 'The Air Filter 17801-28010 is a high-quality engine air filter designed to deliver superior filtration performance for Toyota vehicles. It effectively removes dust, dirt, and other airborne particles, ensuring clean airflow to the engine for improved combustion and performance. Built to meet OEM standards, it offers reliable protection and a perfect fit.', 'uploads/68ea985d65bed_1760204893.png', 'Type: Engine Air Filter\r\nModel Code: 17801-28010\r\nMaterial: High-efficiency pleated paper filter\r\nFrame: Durable rubber sealing edge for tight fit\r\nFiltration Efficiency: ?99% dust and particle capture\r\nStandard: OEM Equivalent / ISO Certified\r\nInstallation: Direct fit—easy to replace', 'Compatible with:\r\nToyota Crown', 'Active', '2025-10-11 11:36:48', '2025-10-21 13:23:05'),
(42, 'Air Filter', '17801-B1010', 'Air Filters', 250.00, 'The Air Filter 17801-B1010 is a premium-quality engine air filter designed to maintain clean airflow to the engine. It effectively traps dust, dirt, and debris, ensuring optimal combustion efficiency, reduced wear, and improved engine performance. Built to match OEM standards, this filter guarantees reliability and easy installation.', 'uploads/68eb484a7472c_1760249930.jpeg', 'Type: Engine Air Filter\r\nModel Code: 17801-B1010\r\nMaterial: Multi-layer pleated paper filtration media\r\nFrame: High-durability rubber sealing gasket\r\nFiltration Efficiency: Up to 99% particle capture\r\nStandard: OEM Equivalent / ISO Certified\r\nInstallation: Direct-fit replacement', 'Compatible with:\r\nToyota Wish (New Model)', 'Active', '2025-10-11 11:37:46', '2025-10-21 13:26:40'),
(43, 'Air Filter', 'ZJ01-13-Z40', 'Air Filters', 250.00, 'The Air Filter ZJ01-13-Z40 provides superior engine protection and optimal airflow for enhanced performance and fuel efficiency. Designed to meet or exceed OEM standards, this filter effectively captures dust, debris, and other contaminants to ensure clean air intake and reliable engine operation.', 'uploads/68eb32ccafb6a_1760244428.png', 'Type: Engine Air Filter\r\nModel Code: ZJ01-13-Z40\r\nMaterial: Multi-layer pleated paper filtration media\r\nFrame: Durable rubber sealing edge\r\nFiltration Efficiency: Up to 99% particle capture\r\nStandard: OEM Equivalent / ISO Certified\r\nInstallation: Direct-fit replacement', 'Compatible with:\r\nMazda Verisa\r\nMazda Demio\r\nMazda Axela', 'Active', '2025-10-11 11:38:37', '2025-10-21 13:28:45'),
(44, 'Air Filter', 'E452L', 'Air Filters', 4500.00, 'The Air Filter E452L is a premium heavy-duty air filter designed for Renault trucks, delivering exceptional engine protection and performance in all driving conditions. Engineered with high-quality filter media, it ensures maximum dust and debris capture while maintaining optimal airflow for improved fuel efficiency and reduced engine wear.', 'uploads/68eb32f6eeb2f_1760244470.png', 'Type: Heavy-Duty Engine Air Filter\r\nModel Code: E452L\r\nMaterial: High-efficiency pleated filter paper\r\nFrame: Reinforced rubber or polyurethane seal\r\nFiltration Efficiency: Up to 99% of airborne particles\r\nTemperature Resistance: -40°C to +100°C\r\nStandard: OEM Equivalent / ISO 9001 Certified\r\nInstallation: Direct-fit replacement, no modification needed', 'Compatible with:\r\nRenault Trucks (Various models)', 'Active', '2025-10-11 11:39:05', '2025-10-21 13:30:41'),
(45, 'Air Filter', 'ME017242', 'Air Filters', 700.00, 'The Air Filter ME017242 is a high-performance, heavy-duty air filter designed for Mitsubishi Canter 4D32 engines. Built with premium filtration materials, it provides superior protection against dust, dirt, and other airborne contaminants, ensuring clean airflow and optimal engine efficiency.', 'uploads/68ea96493d9fb_1760204361.png', 'Type: Engine Air Filter\r\nModel Code: ME017242\r\nMaterial: Multi-layer pleated filter paper\r\nFrame: Durable rubber or polyurethane sealing\r\nFiltration Efficiency: Up to 99% of particles ?5 microns\r\nTemperature Range: -40°C to +100°C\r\nStandard: OEM Equivalent / ISO 9001 Certified\r\nInstallation: Direct-fit replacement (no modifications needed)', 'Compatible with:\r\nMitsubishi Canter 4D32', 'Active', '2025-10-11 11:40:14', '2025-10-21 13:32:36'),
(46, 'Air Filter', '17801-OC010', 'Air Filters', 700.00, 'The Air Filter 17801-OC010 is a premium-quality filter engineered for Toyota Vigo D4D models. It effectively removes dust, dirt, and other airborne contaminants from the intake air, ensuring clean airflow and improved engine performance. Built to meet or exceed OEM standards, it guarantees durability, reliability, and superior engine protection.', 'uploads/68ea9636854f5_1760204342.jpeg', 'Type: Engine Air Filter\r\nModel Code: 17801-OC010\r\nFilter Material: Multi-layer synthetic fiber\r\nOuter Frame: High-strength rubber or plastic seal\r\nFiltration Efficiency: 98–99%\r\nQuality Standard: OEM equivalent / ISO certified\r\nFitment: Direct replacement, no modification required', 'Compatible with:\r\nToyota Vigo D4D\r\nOther Toyota diesel models using the same filter design', 'Active', '2025-10-11 11:41:21', '2025-10-21 13:34:32'),
(47, 'Air Filter', '16546-AW002A', 'Air Filters', 600.00, 'The Air Filter 16546-AW002A is a genuine-quality replacement filter designed specifically for Nissan Hardbody NP300. Engineered with precision, it ensures clean airflow to the engine, improving combustion efficiency and extending engine life. This filter offers excellent dust-holding capacity and consistent filtration performance even in tough driving environments.', 'uploads/68eb3b0c6ea72_1760246540.jpeg', 'Type: Engine Air Filter\r\nModel Code: 16546-AW002A\r\nMaterial: Multi-layer pleated paper filter\r\nFrame: Reinforced rubber or polyurethane seal\r\nFiltration Efficiency: Up to 99%\r\nStandard: OEM Equivalent / ISO 9001 Certified\r\nFitment: Direct replacement (no modification required)', 'Compatible with:\r\nNissan Hardbody NP300\r\nOther selected Nissan models using the same air intake design', 'Active', '2025-10-11 11:42:25', '2025-10-22 06:40:27'),
(48, 'Air Filter', '17801-61030', 'Air Filters', 600.00, 'The Air Filter 17801-61030 is a high-quality replacement filter designed for Toyota Land Cruiser Pickup models. Built to OEM standards, it provides reliable engine protection by effectively trapping dust, dirt, and other airborne particles. Its durable construction ensures long-lasting performance even in rugged driving conditions.', 'uploads/68eb3b6059b6c_1760246624.jpeg', 'Type: Engine Air Filter\r\nModel Code: 17801-61030\r\nMaterial: Multi-layer pleated synthetic fiber\r\nFrame: Reinforced rubber or polyurethane sealing\r\nFiltration Efficiency: Up to 99%\r\nAirflow Design: Optimized for superior engine breathing and fuel efficiency\r\nStandard: OEM Equivalent / ISO Certified\r\nInstallation: Direct-fit replacement (no modifications required)', 'Compatible with:\r\nToyota Land Cruiser Pickup\r\nOther Toyota diesel models with the same air intake system', 'Active', '2025-10-11 11:43:17', '2025-10-22 06:43:11'),
(49, 'Air Filter', 'E541L', 'Air Filters', 4500.00, 'The E541L Air Filter is a premium-quality filtration component engineered for DAF Trucks. Designed to deliver maximum airflow and superior dust-holding capacity, it ensures clean air intake for improved engine performance, reduced fuel consumption, and longer service life. Built to meet OEM standards, this filter is ideal for both on-road and heavy-duty applications.', 'uploads/68eb340b45cc4_1760244747.png', 'Type: Engine Air Filter\r\nModel Code: E541L\r\nFilter Media: High-efficiency synthetic fiber\r\nFrame Material: Reinforced polyurethane sealing\r\nFiltration Efficiency: Up to 99% of particles ?5 microns\r\nOperating Temperature: -40°C to +100°C\r\nAirflow Resistance: Optimized for engine efficiency\r\nQuality Standard: OEM Equivalent / ISO 9001 Certified\r\nInstallation: Direct-fit replacement (no modification required)', 'Compatible with:\r\nDAF Trucks\r\nOther heavy-duty commercial vehicles using similar air systems', 'Active', '2025-10-11 11:44:19', '2025-10-22 06:48:58'),
(50, 'Air Filter', 'AB39-9601', 'Air Filters', 800.00, 'The AB39-9601 Air Filter is a high-performance filtration unit engineered to protect your Ford Ranger’s engine from harmful dust, dirt, and contaminants. Designed with premium filter media and a precision-molded seal, it ensures consistent airflow, optimal combustion, and maximum engine efficiency under all driving conditions.', 'uploads/68eb4786398a4_1760249734.png', 'Type: Engine Air Filter\r\nModel Code: AB39-9601\r\nFilter Media: High-efficiency cellulose + synthetic blend\r\nFrame Material: Reinforced rubber sealing edge\r\nFiltration Efficiency: ?99% of particles ?5 microns\r\nOperating Temperature Range: -40°C to +100°C\r\nAirflow Resistance: Low, for improved fuel economy\r\nStandards: OEM Equivalent / ISO 9001 Certified\r\nInstallation: Direct-fit replacement (no modification required)', 'Compatible with:\r\nFord Ranger (selected models)\r\nOther vehicles using filter model AB39-9601', 'Active', '2025-10-11 11:44:26', '2025-10-22 06:51:47'),
(51, 'Air Filter', '17801-B2050', 'Air Filters', 300.00, 'The 17801-B2050 Air Filter is an OEM-quality replacement designed to deliver clean, unrestricted airflow to your Daihatsu Mira engine. Built using durable, high-efficiency filter media, it ensures effective dust capture, enhanced fuel economy, and long engine life. Ideal for daily use and harsh driving conditions.', 'uploads/68ea96bc6cccd_1760204476.png', 'Type: Engine Air Filter\r\nModel Code: 17801-B2050\r\nFilter Media: Multi-layer cellulose/synthetic fiber\r\nFrame Material: High-durability rubber gasket\r\nFiltration Efficiency: ?98% of fine particles\r\nAirflow: Optimized for engine performance and fuel efficiency\r\nTemperature Range: -40°C to +100°C\r\nCertification: OEM Equivalent / ISO 9001 Certified\r\nInstallation: Direct-fit, easy to replace', 'Used for:\r\nDaihatsu Mira\r\nCompatible with select small Daihatsu and Toyota kei-car engines', 'Active', '2025-10-11 11:45:38', '2025-10-22 06:53:52'),
(53, 'Air Filter', '13780-50M00', 'Air Filters', 300.00, 'The 13780-50M00 Air Filter provides dependable engine protection for Suzuki vehicles, ensuring clean airflow and consistent performance. Built from premium filter media, it effectively traps dust, dirt, and debris to prevent engine wear and maintain optimal combustion efficiency.', 'uploads/68ea96d9dc307_1760204505.png', 'Filter Type: Engine Air Filter\r\nModel Code: 13780-50M00\r\nMaterial: High-grade paper element with rubber sealing gasket\r\nFiltration Efficiency: ?98%\r\nCompatibility: Direct OEM replacement\r\nTemperature Resistance: -40°C to +110°C\r\nStandard: ISO 9001 / OEM Quality\r\nInstallation: Quick-fit, no modification required', 'Used for:\r\nSuzuki models (varies by engine type)\r\nCommonly used in Suzuki compact cars and small vans', 'Active', '2025-10-11 11:47:28', '2025-10-22 06:57:44'),
(54, 'Air Filter', '1780-78110', 'Air Filters', 1500.00, 'The 1780-78110 Air Filter is engineered for superior filtration performance and durability in Hino 300 trucks. Designed with high-efficiency filter media, it captures dust, debris, and contaminants to ensure clean airflow, protecting the engine and improving performance under demanding operating conditions.', 'uploads/68eb3bc0867e6_1760246720.jpeg', 'Filter Type: Heavy-duty Engine Air Filter\r\nModel Code: 1780-78110\r\nMaterial: Reinforced paper media with rubber sealing edge\r\nFiltration Efficiency: ?99%\r\nApplication Type: Commercial / Truck\r\nStandard: OEM Equivalent – ISO 9001 Certified\r\nTemperature Resistance: Up to +120°C\r\nInstallation: Direct OEM replacement—easy to install', 'USED FOR HINO 300', 'Active', '2025-10-11 11:49:13', '2025-10-22 06:59:26'),
(55, 'Air Filter', '17801-17010/20', 'Air Filters', 1000.00, 'The 17801-17010/20 Air Filter is a premium-quality replacement designed to deliver maximum filtration efficiency for Toyota Land Cruiser V8 (Old Model). It ensures clean air intake, enhancing engine performance, fuel efficiency, and longevity by preventing harmful particles from entering the engine.', 'uploads/68eb3c291c716_1760246825.jpeg', 'Filter Type: Engine Air Filter\r\nOEM Reference: 17801-17010 / 17801-17020\r\nMaterial: High-density synthetic fiber media\r\nFiltration Efficiency: ?99%\r\nTemperature Range: -40°C to +120°C\r\nConstruction: Heavy-duty frame with precision sealing gasket\r\nStandard Compliance: ISO/TS 16949, OEM equivalent\r\nInstallation: Direct fit—no modification required', 'Used for:\r\nTOYOTA LAND CRUISER V8 (Old Model)\r\nTOYOTA LAND CRUISER 100 SERIES', 'Active', '2025-10-11 11:50:16', '2025-10-22 07:03:07'),
(57, 'Air Filter', 'E118L', 'Air Filters', 4500.00, 'The E118L Original Air Filter is designed to meet the high-performance demands of Mercedes-Benz old model trucks. It provides superior engine protection by efficiently trapping dust, dirt, and other airborne contaminants before they enter the engine, ensuring long service life and optimal fuel efficiency.', 'uploads/68ea959df2f62_1760204189.png', 'Filter Type: Heavy-Duty Air Filter\r\nOEM Reference: E118L\r\nMaterial: Reinforced paper and metal mesh construction\r\nFiltration Efficiency: ?99% particle separation\r\nTemperature Resistance: Up to 120°C\r\nDimensions: OEM-standard fit for direct installation\r\nCertification: ISO/TS 16949 – Quality Assured\r\nMaintenance Interval: As per manufacturer’s recommendation', 'Used for:\r\nMercedes-Benz Old Model Trucks\r\n(e.g., Actros, Axor, and Atego Classic models)', 'Active', '2025-10-11 11:52:26', '2025-10-22 07:04:53'),
(58, 'Air Filter', '17801-54100', 'Air Filters', 500.00, 'The 17801-54100 Air Filter is engineered for high-efficiency filtration and reliable performance. Designed to protect engines by effectively trapping dust, dirt, and debris, it ensures smooth airflow and extended engine life for 5L truck models.', 'uploads/68eb3cd237e0c_1760246994.jpeg', 'Filter Type: Engine Air Filter\r\nOEM Reference: 17801-54100\r\nMaterial: Premium paper media with reinforced frame\r\nFiltration Efficiency: ?99% for particles ?5 microns\r\nTemperature Resistance: Up to 120°C\r\nFit Type: OEM-standard, direct replacement\r\nCertification: ISO/TS 16949 – Quality Certified\r\nRecommended Replacement: Every 10,000–15,000 km (depending on use)', 'Used for:\r\nTOYOTA 5L Trucks\r\n(Includes models such as Toyota Dyna, Hilux 5L, and Hiace 5L)', 'Active', '2025-10-11 11:52:42', '2025-10-22 07:07:15'),
(59, 'Air Filter', '885409052516', 'Air Filters', 3200.00, 'The Air Filter 885409052516 is designed for heavy-duty TATA Truck (2516) applications. It provides superior engine protection by trapping dust, dirt, and debris while maintaining optimal airflow. Built to withstand harsh road and construction environments, this filter ensures long-lasting performance and reliability.', 'uploads/68eb3d20c7755_1760247072.png', 'Filter Type: Engine Air Filter\r\nOEM Reference: 885409052516\r\nMaterial: Heavy-duty pleated paper with reinforced metal mesh\r\nFiltration Efficiency: ?99% for particles ?5 microns\r\nFit Type: OEM-standard, direct replacement\r\nCompatible Model: TATA Truck 2516\r\nRecommended Service Interval: Every 15,000–20,000 km (or as per manufacturer schedule)\r\nCertification: ISO/TS 16949 – Certified for quality and reliability', 'Used for:\r\nTATA 2516 Truck\r\nSuitable for construction, transport, and industrial fleet vehicles', 'Active', '2025-10-11 11:53:43', '2025-10-22 07:11:52'),
(60, 'Air Filter', '17801-3360/70', 'Air Filters', 2500.00, 'The Air Filter 17801-3360/70 is a high-efficiency replacement filter specifically designed for HINO 500 trucks. It ensures optimal engine performance by preventing dust, dirt, and debris from entering the intake system—helping extend engine life and improve fuel efficiency.', 'uploads/68eb3ca323b30_1760246947.png', 'Filter Type: Engine Air Filter\r\nOEM Reference: 17801-3360/70\r\nMaterial: Multi-layer pleated filter paper with metal mesh reinforcement\r\nFiltration Efficiency: ?99% for particles ?5 microns\r\nFit Type: Direct OEM replacement\r\nCompatible Model: HINO 500 Series\r\nRecommended Service Interval: Every 15,000–20,000 km (depending on operating conditions)\r\nQuality Certification: ISO/TS 16949 Certified', 'Used for:\r\nHINO 500 Trucks\r\nIdeal for logistics, construction, and long-haul operations', 'Active', '2025-10-11 11:54:38', '2025-10-22 07:13:51'),
(61, 'Air Filter', '1-14215203-0', 'Air Filters', 4200.00, 'The Air Filter 1-14215203-0 is a high-performance filtration solution engineered for ISUZU CXZ trucks. Designed to deliver exceptional dust-holding capacity and superior filtration efficiency, it protects your engine from harmful contaminants while maintaining maximum airflow for optimal performance.', 'uploads/68ea95c56c8f6_1760204229.png', 'Filter Type: Heavy-Duty Engine Air Filter\r\nOEM Reference: 1-14215203-0\r\nMaterial: High-efficiency pleated filter media\r\nFiltration Efficiency: ?99% (ISO-tested)\r\nOuter Diameter: 188 mm\r\nInner Diameter: 100 mm\r\nHeight: 410 mm\r\nCompatible Model: ISUZU CXZ\r\nQuality Standard: ISO/TS 16949 Certified\r\nRecommended Replacement: Every 15,000–25,000 km or as per manufacturer schedule', 'Used for:\r\nISUZU CXZ Trucks\r\nCommon in long-distance haulage and construction fleet engines', 'Active', '2025-10-11 11:55:43', '2025-10-22 07:18:24'),
(62, 'Air Filter', '8-97941-655-0/8-97944-570-0', 'Air Filters', 400.00, 'The Air Filter 8-97941-655-0 / 8-97944-570-0 is engineered to deliver reliable filtration performance for ISUZU D-MAX (Old Model). It provides maximum dust capture and airflow balance, ensuring long-lasting engine protection and efficiency in both urban and off-road environments.', 'uploads/68eb3d084b246_1760247048.png', 'Filter Type: Engine Air Filter\r\nOEM References: 8-97941-655-0 / 8-97944-570-0\r\nMaterial: High-efficiency pleated filter paper\r\nFiltration Efficiency: ?99%\r\nCompatible Vehicle: ISUZU D-MAX (Old Model)\r\nQuality Standard: ISO/TS 16949 Certified\r\nReplacement Interval: Every 10,000–15,000 km (or as per manufacturer guidelines)', '? Suitable for ISUZU D-MAX Old Model\r\n? Ideal for pickup and light-duty truck engines', 'Active', '2025-10-11 11:56:47', '2025-10-22 07:20:11'),
(64, 'Air Filter', 'E1013l', 'Air Filters', 4500.00, 'The E1013L Air Filter is designed for maximum engine protection and performance in Scania P380 trucks. Built with premium filtration media, it effectively captures dust and debris, ensuring optimal airflow and improved engine efficiency under heavy-duty operations.', 'uploads/68eb3c778abc1_1760246903.jpeg', 'Filter Type: Heavy-Duty Engine Air Filter\r\nOEM Reference: E1013L\r\nCompatible Vehicle: Scania P380 Trucks\r\nFiltration Efficiency: ?99%\r\nMaterial: Multi-layer pleated filter paper with metal mesh reinforcement\r\nStandard: ISO/TS 16949 Certified\r\nReplacement Interval: Every 15,000–20,000 km (or per manufacturer recommendation)', '? Ideal for Scania P380\r\n? Suitable for long-haul and industrial transport vehicles', 'Active', '2025-10-11 11:59:44', '2025-10-22 07:21:47'),
(65, 'Air Filter', 'E451L ', 'Air Filters', 5500.00, 'The E451L Air Filter delivers exceptional performance and long-lasting engine protection for Scania trucks. Designed with premium-grade filtration media, it traps dust, dirt, and harmful contaminants to maintain clean airflow and boost engine efficiency in heavy-duty transport environments.', 'uploads/68eb32385362c_1760244280.png', 'Filter Type: Heavy-Duty Engine Air Filter\r\nOEM Reference: E451L\r\nCompatible Vehicles: Scania Trucks\r\nFiltration Efficiency: ?99%\r\nMaterial: Multi-layer synthetic media with reinforced mesh\r\nStandard: ISO/TS 16949 Certified\r\nReplacement Interval: Every 15,000–25,000 km (or per manufacturer recommendation)', '? Designed for Scania Truck Series\r\n? Ideal for long-distance and industrial transport operations', 'Active', '2025-10-11 12:01:16', '2025-10-22 07:23:19'),
(66, 'Air Filter', '64.08301.0008/2518.', 'Air Filters', 4500.00, 'High-performance Air Filter engineered for superior dust retention and maximum airflow efficiency. This durable filter is ideal for TATA 2518 trucks, ensuring long engine life and consistent performance under heavy-duty operating conditions.', 'uploads/68eb3daaa03ed_1760247210.jpeg', 'Filter Type: Heavy-Duty Engine Air Filter\r\nOEM Reference: 64.08301.0008 / 2518\r\nCompatible Vehicle: TATA 2518\r\nEfficiency: ?99% filtration\r\nMaterial: High-quality synthetic media with reinforced mesh\r\nStandard: ISO/TS 16949 Certified\r\nReplacement Interval: 15,000–25,000 km or per manufacturer’s service schedule', '? Designed for TATA 2518 Trucks\r\n? Suitable for heavy transport and industrial applicatio', 'Active', '2025-10-11 12:02:20', '2025-10-22 07:24:55'),
(67, 'Air Filter', '5-87610-290-0', 'Air Filters', 1500.00, 'Durable air filter designed to deliver exceptional engine protection and airflow efficiency. Perfect for Isuzu NMR and NLM 4.3 new model trucks, ensuring reliable performance and extended engine life under demanding driving conditions.', 'uploads/68eb47bb336d9_1760249787.jpeg', 'Filter Type: Heavy-Duty Engine Air Filter\r\nOEM Reference: 5-87610-290-0\r\nCompatible Models: Isuzu NMR, NLM (4.3L New Model)\r\nEfficiency: ?99% Filtration\r\nMaterial: Synthetic high-flow media with strong sealing gasket\r\nStandard: ISO/TS 16949 Certified\r\nService Life: 15,000–25,000 km (depending on conditions)', '? Isuzu NMR (4.3 New Model)\r\n? Isuzu NLM (4.3 New Model)\r\n? Ideal for commercial trucks and delivery fleets', 'Active', '2025-10-11 12:02:39', '2025-10-22 07:26:21'),
(68, 'Air Filter', '8-98071421-0', 'Air Filters', 2500.00, 'Premium air filter designed for Isuzu FRR 90 New Model trucks. Built for durability and maximum airflow efficiency, ensuring optimal engine performance and extended service life under tough operating conditions.', 'uploads/68eb3dec8d653_1760247276.jpeg', 'Filter Type: Engine Air Filter\r\nOEM Reference: 8-98071421-0\r\nCompatible Models: Isuzu FRR 90 (New Model)\r\nFiltration Efficiency: ?99%\r\nMaterial: Multi-layer synthetic media with high dust-holding capacity\r\nSeal Type: Reinforced rubber gasket\r\nStandard: ISO/TS 16949 Certified\r\nService Life: 15,000–25,000 km (depending on road conditions)', 'Isuzu FRR 90 (New Model)\r\nSuitable for commercial and fleet vehicles', 'Active', '2025-10-11 12:03:25', '2025-10-24 09:56:36'),
(69, 'Air Filter', '8-94156-052', 'Air Filters', 800.00, 'High-performance air filter designed for Isuzu NKR 3.6 engines. Ensures reliable filtration, optimal engine airflow, and enhanced performance under all operating conditions.', 'uploads/68eb3dfbe4527_1760247291.jpeg', 'Filter Type: Engine Air Filter\r\nOEM Reference: 8-94156-052\r\nCompatible Models: Isuzu NKR 3.6\r\nFiltration Efficiency: ?99%\r\nMaterial: High-grade pleated filter paper\r\nSeal Type: Durable rubber gasket\r\nService Life: 15,000–20,000 km\r\nStandard: ISO/TS 16949 Certified', 'Isuzu NKR 3.6 (Truck Series)\r\nSuitable for light and medium-duty vehicles', 'Active', '2025-10-11 12:05:04', '2025-10-24 09:55:27'),
(70, 'Air Filter', '1-1421515-3', 'Air Filters', 1500.00, 'A high-quality air filter engineered to deliver reliable engine protection and optimal airflow. Designed to trap dust, dirt, and other contaminants, ensuring maximum engine efficiency and extended service life.', 'uploads/68eb3dcd1518a_1760247245.jpeg', 'Filter Type: Dry Element Air Filter\r\nMaterial: Heavy-duty paper filtration media\r\nOuter Diameter: Approx. 180 mm (adjustable per OEM spec)\r\nInner Diameter: Approx. 90 mm\r\nHeight: Approx. 250 mm\r\nEfficiency: ? 99% particulate filtration\r\nCompatible Standard: OEM replacement / ISO certified quality', 'Suitable for ISUZU NQR and NPR single models\r\nIdeal for commercial trucks, delivery vehicles, and industrial applications', 'Active', '2025-10-11 12:05:53', '2025-10-24 10:00:02'),
(71, 'Air Filter', '1-14215153-0', 'Air Filters', 1650.00, 'Premium-quality air filter designed to ensure superior engine protection and long-lasting performance. Built to effectively trap dust, dirt, and debris, maintaining clean airflow and enhancing fuel efficiency.', 'uploads/68ea94733eabc_1760203891.png', 'Filter Type: Dry Element Air Filter\r\nMaterial: Heavy-duty cellulose and synthetic fiber media\r\nOuter Diameter: Approx. 195 mm (varies per OEM specification)\r\nInner Diameter: Approx. 100 mm\r\nHeight: Approx. 260 mm\r\nFiltration Efficiency: ? 99% particulate retention\r\nOEM Standard: Direct replacement for ISUZU FRR, FTR, FSR (4.3 Double)\r\nCertification: ISO/TS 16949 Compliant', 'ISUZU FRR 4.3 Double\r\nISUZU FTR 4.3 Double\r\nISUZU FSR 4.3 Double\r\nSuitable for medium-duty trucks and commercial fleet vehicles.', 'Active', '2025-10-11 12:06:51', '2025-10-24 10:01:48'),
(73, 'Air Filter', 'ME073597', 'Air Filters', 2500.00, 'Air Filter', 'uploads/68eb3d9671428_1760247190.jpeg', '', 'USED FOR FH NEW, FUSO FIGHTER', 'Active', '2025-10-11 12:08:06', '2025-10-12 05:33:10'),
(75, 'Air Filter', 'ME033717', 'Air Filters', 1500.00, 'High-quality air filter engineered to deliver optimal engine protection and airflow performance. Designed for heavy-duty applications, this filter ensures clean intake air and extends engine life by efficiently trapping harmful contaminants.', 'uploads/68eb3d80e7dd8_1760247168.jpeg', 'Filter Type: Primary Air Filter\r\nMaterial: Heavy-duty paper element with metal mesh support\r\nOuter Diameter: Approx. 195 mm (OEM standard)\r\nInner Diameter: Approx. 100 mm\r\nHeight: Approx. 270 mm\r\nFiltration Efficiency: ? 99%\r\nOEM Reference: ME033717\r\nConstruction: Reinforced with steel end caps for durability\r\nQuality Standard: ISO/TS 16949 Certified', 'Mitsubishi FH215 (Old Models)\r\nCompatible with other Mitsubishi trucks of similar engine capacity', 'Active', '2025-10-11 12:09:34', '2025-10-24 10:04:01'),
(76, 'Oil Filter', '8-98165071-0', 'Oil Filters', 200.00, 'Durable engine oil filter designed to provide superior protection by removing contaminants, ensuring clean oil flow, and extending engine life. Built with precision to meet OEM standards for performance and reliability.', 'uploads/68ede26c75d41_1760420460.jpeg', 'Filter Type: Full-flow Spin-on Oil Filter\r\nMaterial: High-efficiency synthetic media with steel casing\r\nThread Size: M20 × 1.5 (Standard)\r\nOuter Diameter: Approx. 80 mm\r\nHeight: Approx. 95 mm\r\nBypass Valve Pressure: 1.2 bar\r\nAnti-Drain Back Valve: Yes\r\nFiltration Efficiency: ? 98%\r\nOEM Reference: 8-98165071-0\r\nQuality Standard: ISO/TS 16949 Certified', 'ISUZU NPR/NKR/NQR Series\r\nISUZU D-MAX\r\nCompatible with similar diesel engines requiring OEM spec filter 8-98165071-0', 'Active', '2025-10-14 05:37:51', '2025-10-24 12:33:29'),
(77, 'Oil Filter', '893396375-4', 'Oil Filters', 950.00, 'oil filter', 'uploads/68ede22b0a5ea_1760420395.jpeg', '', '', 'Active', '2025-10-14 05:39:55', '2025-10-14 05:39:55'),
(78, 'Oil Filter', '15208-65F00', 'Oil Filters', 125.00, 'High-quality engine oil filter engineered to provide exceptional filtration performance and protect your engine from harmful contaminants. This filter ensures clean, consistent oil flow, improving engine longevity and maintaining optimal performance even under tough driving conditions.', 'uploads/68ede2de19ad0_1760420574.jpeg', 'Filter Type: Spin-on Oil Filter\r\nThread Size: M20 × 1.5\r\nOuter Diameter: ~80 mm\r\nHeight: ~85 mm\r\nFiltration Media: High-efficiency cellulose/synthetic blend\r\nBypass Valve Pressure: 1.2 bar\r\nAnti-Drain Back Valve: Yes (for cold start protection)\r\nFiltration Efficiency: ? 98%\r\nQuality Standard: ISO/TS 16949 Certified\r\nOEM Reference: 15208-65F00', 'Nissan models—including Sunny, Primera, Patrol, Caravan, Navara, Hardbody, and Urvan\r\nSubaru models with compatible oil systems\r\nSuzuki and Mazda petrol engines using OEM reference 15208-65F00', 'Active', '2025-10-14 05:42:54', '2025-10-24 12:35:38'),
(79, 'Oil Filter', 'MD135737', 'Oil Filters', 130.00, 'Premium-quality engine oil filter designed to deliver consistent oil purification and protect your engine from wear and contamination. The MD135737 filter ensures smooth oil flow, stable pressure, and enhanced engine performance — ideal for both passenger and commercial vehicles.', 'uploads/68ede32dad3c5_1760420653.jpeg', 'Filter Type: Spin-on Oil Filter\r\nThread Size: M20 × 1.5\r\nOuter Diameter: ~80 mm\r\nHeight: ~85 mm\r\nFilter Media: High-efficiency cellulose/synthetic blend\r\nBypass Valve Setting: 1.2 bar\r\nAnti-Drain Back Valve: Yes (for improved cold start lubrication)\r\nFiltration Efficiency: ? 98%\r\nMaterial: Corrosion-resistant steel casing\r\nQuality Standard: ISO/TS 16949 Certified\r\nOEM Reference: MD135737', 'Mitsubishi vehicles—Lancer, Pajero, Delica, Galant, and Colt\r\nHyundai and Kia models with compatible 1.6L–2.4L engines\r\nSuitable for selected Proton and Dodge models with Mitsubishi engines', 'Active', '2025-10-14 05:44:13', '2025-10-24 12:37:40'),
(80, 'Oil Filter', '90915-03002', 'Oil Filters', 130.00, 'High-quality engine oil filter engineered for maximum engine protection and extended service intervals. The 90915-03002 oil filter efficiently removes carbon, metal particles, and sludge from engine oil, ensuring cleaner lubrication and optimal performance. Designed to meet or exceed OEM standards for fit and reliability.', 'uploads/68ede3f3a2e94_1760420851.jpeg', 'Filter Type: Spin-on oil filter\r\nThread Size: M20 × 1.5\r\nOuter Diameter: ~80 mm\r\nHeight: ~85 mm\r\nFilter Media: Multi-layer cellulose/synthetic fiber\r\nBypass Valve Pressure: 1.2 bar\r\nAnti-Drain Back Valve: Yes\r\nSeal Material: Nitrile rubber gasket\r\nCasing Material: Heavy-duty corrosion-resistant steel\r\nFiltration Efficiency: ? 98% (at 20 microns)\r\nStandard Compliance: ISO/TS 16949 Certified\r\nOEM Reference: Toyota Genuine 90915-03002', 'Toyota Corolla (1.5L, 1.6L, 1.8L engines)\r\nToyota Hilux (2.0L, 2.7L petrol engines)\r\nToyota RAV4, Camry, Premio, and Wish\r\nLexus IS200/RX300 models\r\nSuitable for select Daihatsu and Subaru models using Toyota engines', 'Active', '2025-10-14 05:47:31', '2025-10-24 12:40:10'),
(81, 'Oil Filter', '15208-H8911', 'Oil Filters', 160.00, 'The Oil Filter 15208-H8911 delivers dependable filtration performance for modern engines. Engineered with high-efficiency media, this filter removes contaminants such as carbon, sludge, and metallic debris, ensuring clean oil circulation and extended engine life. It provides OEM-level reliability for both passenger and commercial vehicles.', 'uploads/68ede44e1ce05_1760420942.jpeg', 'Thread Size: M20 × 1.5\r\nOuter Diameter: ~80 mm\r\nHeight: ~90 mm\r\nFilter Media: High-capacity cellulose/synthetic blend\r\nBypass Valve: 1.2 bar\r\nAnti-Drain Back Valve: Yes (Silicone)\r\nSealing Gasket: Nitrile rubber\r\nShell Material: Heavy-duty corrosion-resistant steel\r\nEfficiency: ? 98% @ 20 microns\r\nQuality Standard: ISO/TS 16949 Certified\r\nOEM Reference: Nissan Genuine 15208-H8911', 'Nissan Sunny / AD Van / March / Tiida\r\nNissan Wingroad / Primera / Bluebird Sylphy\r\nNissan Note / Cube / Latio / Micra\r\nInfiniti G20 and QX series\r\nAlso compatible with select Mazda and Datsun models', 'Active', '2025-10-14 05:49:02', '2025-10-24 12:42:42'),
(82, 'Fuel Filter', '0-4152-38020', 'Fuel Filters', 300.00, 'The Fuel Filter 0-4152-38020 is designed to provide superior protection for fuel injection systems by effectively removing contaminants such as dirt, rust, and water from diesel or petrol fuel. Built with precision-engineered components, it ensures optimal engine performance, smooth operation, and longer injector life.', 'uploads/68ede4b0277f8_1760421040.jpeg', 'Filter Type: Inline / Cartridge fuel filter\r\nOuter Diameter: ~85 mm\r\nHeight: ~120 mm\r\nMicron Rating: 5–10 µm\r\nFilter Media: Multi-layer synthetic/cellulose blend\r\nWater Separation Efficiency: ?95%\r\nFlow Direction: Inlet ? Outlet (marked on housing)\r\nPressure Resistance: Up to 10 bar\r\nSealing Gasket: Nitrile rubber\r\nQuality Standard: ISO/TS 16949 Certified\r\nOEM Reference: Bosch 0 4152 38020', 'Used in diesel and petrol engines, including:\r\nIsuzu trucks (FRR, NPR, NQR series)\r\nMitsubishi Canter/Fuso models\r\nToyota Dyna/Hilux diesel\r\nNissan Diesel (UD series)\r\nKomatsu and construction machinery\r\nSuitable for a wide range of Japanese and European commercial vehicles', 'Active', '2025-10-14 05:50:40', '2025-10-24 12:46:10'),
(83, 'Oil Filter', '04152-37010', 'Oil Filters', 130.00, 'The Oil Filter 04152-37010 delivers superior filtration performance, ensuring clean and efficient engine lubrication. Designed with high-quality media and durable housing, it removes contaminants such as carbon, metal particles, and sludge, protecting the engine from premature wear and enhancing longevity.', 'uploads/68ede9a468714_1760422308.jpeg', 'Filter Type: Spin-on / Cartridge\r\nOuter Diameter: ~80 mm\r\nHeight: ~100 mm\r\nThread Size: Standard (M20x1.5 / 3/4”-16UNF depending on OEM)\r\nFilter Media: Multi-layer synthetic fiber\r\nMicron Rating: 20 µm\r\nBypass Valve: Integrated (Pressure relief 1.0–1.2 bar)\r\nAnti-Drain Back Valve: Yes\r\nGasket Material: Nitrile Rubber (NBR)\r\nOperating Temperature: ?30°C to 150°C\r\nOEM Reference: Toyota Genuine 04152-37010\r\nQuality Standard: ISO/TS 16949 Certified', 'Toyota Land Cruiser Prado / Hilux / Hiace\r\nLexus GX and RX series\r\nDaihatsu and other Japanese vehicles\r\nCompatible with several petrol and diesel engines using the same OEM spec', 'Active', '2025-10-14 06:11:48', '2025-10-24 12:49:01'),
(84, 'Oil Filter', '04152-38010', 'Oil Filters', 129.98, 'The Oil Filter 04152-38010 is engineered to deliver reliable, long-lasting engine protection by filtering out harmful particles and contaminants from engine oil. This ensures optimal engine performance, reduced wear, and extended oil life. Ideal for both commercial and passenger vehicle applications.', 'uploads/68edea41549ad_1760422465.jpeg', 'Filter Type: Cartridge / Spin-on (depending on OEM)\r\nOuter Diameter: ~80 mm\r\nHeight: ~100 mm\r\nThread Size: Standard (M20x1.5 / 3/4”-16UNF)\r\nFilter Media: High-efficiency synthetic fiber\r\nMicron Rating: 20 µm nominal\r\nBypass Valve: Integrated (1.0–1.2 bar)\r\nAnti-Drain Back Valve: Yes\r\nGasket Material: Nitrile Rubber (NBR)\r\nOperating Temperature: ?30°C to 150°C\r\nOEM Reference: Toyota Genuine 04152-38010\r\nQuality Standard: ISO/TS 16949 Certified', 'Toyota Hilux / Land Cruiser / Hiace / Fortuner\r\nLexus GX & RX Series\r\nDaihatsu & other Japanese models\r\nSuitable for both diesel and petrol engines matching the same OEM specification', 'Active', '2025-10-14 06:14:25', '2025-10-24 12:51:06');
INSERT INTO `products` (`id`, `name`, `code`, `category`, `price`, `description`, `image`, `specifications`, `applications`, `status`, `created_at`, `updated_at`) VALUES
(85, 'Oil Filter', '197610093-1', 'Oil Filters', 400.00, 'The Oil Filter 197610093-1 provides high-efficiency filtration for modern automotive and industrial engines. Designed to remove harmful impurities and metal particles from engine oil, it ensures smooth lubrication, extended oil life, and superior engine protection under demanding operating conditions.', 'uploads/68ededa9b22e7_1760423337.jpeg', 'Filter Type: Spin-on / Cartridge (OEM-equivalent)\r\nOuter Diameter: ~75–85 mm\r\nHeight: ~95–105 mm\r\nThread Size: M20x1.5 / 3/4\"-16 UNF (varies by model)\r\nFilter Media: Multi-layer synthetic fiber with metal end caps\r\nMicron Rating: 20 µm nominal\r\nBypass Valve: Yes (1.0–1.2 bar)\r\nAnti-Drain Back Valve: Equipped\r\nOperating Pressure: Up to 8 bar\r\nTemperature Range: ?30°C to 150°C\r\nGasket Material: Nitrile / Viton\r\nOEM Reference: Equivalent to select Toyota, Nissan, and Mitsubishi models\r\nQuality Standard: ISO/TS 16949 Certified', 'Passenger vehicles (Toyota, Nissan, Mitsubishi)\r\nLight commercial engines\r\nConstruction and agricultural machinery\r\nDiesel and petrol engines requiring similar OEM fitment', 'Active', '2025-10-14 06:28:57', '2025-10-24 12:53:06'),
(86, 'Oil Filter', '90915-10004', 'Oil Filters', 130.00, 'The Oil Filter 90915-10004 is a premium-quality replacement designed to deliver superior engine protection and performance. It effectively removes contaminants such as carbon, metal debris, and dirt particles from engine oil, ensuring optimal lubrication and reducing engine wear.', 'uploads/68edee9ae995f_1760423578.jpeg', 'Filter Type: Spin-on / Cartridge (OEM equivalent)\r\nThread Size: M20 × 1.5\r\nOuter Diameter: ~65–75 mm\r\nHeight: ~85–95 mm\r\nFilter Media: Multi-layer synthetic/cellulose blend\r\nMicron Rating: 20 µm nominal\r\nBypass Valve: Integrated (1.0 bar)\r\nAnti-Drain Back Valve: Yes (silicone type)\r\nPressure Resistance: Up to 8 bar\r\nTemperature Range: ?30°C to 150°C\r\nGasket Material: Nitrile Rubber / Viton\r\nOEM Cross Reference:\r\nToyota Genuine Part 90915-10004\r\nCompatible with select Toyota and Lexus engines\r\nStandard: ISO/TS 16949 Certified', 'Toyota Corolla, Camry, Hilux, Land Cruiser, RAV4\r\nLexus ES, IS, and RX models\r\nPetrol and diesel engines using equivalent OEM filters\r\nLight commercial and passenger vehicles', 'Active', '2025-10-14 06:32:58', '2025-10-24 12:55:43'),
(87, 'Fuel Filter', '8-94414796-3', 'Oil Filters', 200.00, 'The Fuel Filter 8-94414796-3 is a high-quality replacement designed to maintain clean fuel flow and protect your engine from harmful contaminants. It efficiently traps dirt, rust, and water particles, ensuring optimal engine performance and fuel efficiency.', 'uploads/68edef44e6d17_1760423748.jpeg', 'Filter Type: Inline / Cartridge fuel filter\r\nMaterial: Multi-layer synthetic fiber media\r\nMicron Rating: 10–20 µm\r\nOuter Diameter: ~75 mm\r\nHeight: ~120 mm\r\nInlet/Outlet Size: 8 mm (standard)\r\nFlow Direction: Marked on housing\r\nCompatibility: OEM equivalent to Isuzu/Toyota diesel models\r\nPressure Rating: Up to 7 bar\r\nTemperature Range: ?40°C to 120°C\r\nConstruction: Corrosion-resistant steel housing\r\nSealing: Nitrile rubber O-ring\r\nStandard: ISO/TS 16949 Certified', 'Used in a wide range of diesel and petrol engines, especially for:\r\nIsuzu D-Max, NPR, NQR, and ELF trucks\r\nToyota Hilux diesel variants\r\nOther Japanese light commercial vehicles and pickups', 'Active', '2025-10-14 06:35:48', '2025-10-24 12:58:43'),
(88, 'Fuel Filter', '1-5208-AA100', 'Oil Filters', 150.00, 'The Fuel Filter 1-5208-AA100 provides reliable filtration performance for both petrol and diesel engines. It removes water, rust, and debris from fuel lines to ensure clean fuel delivery and protect critical engine components such as injectors and fuel pumps.', 'uploads/68edefc1aeae1_1760423873.jpeg', 'Type: Inline / Spin-on fuel filter\r\nMaterial: Multi-layer synthetic and cellulose blend\r\nMicron Rating: 10–20 µm\r\nOuter Diameter: ~70 mm\r\nHeight: ~110 mm\r\nThread Size: M20 × 1.5\r\nFilter Media Efficiency: ? 99%\r\nPressure Rating: Up to 8 bar\r\nOperating Temperature: ?40°C to 120°C\r\nStandard Compliance: ISO/TS 16949 Certified\r\nCompatibility: OEM replacement for Nissan, Isuzu, and Toyota small diesel engines', 'Nissan Diesel models\r\nIsuzu Trooper / D-Max / ELF series\r\nToyota Land Cruiser / Hilux\r\nLight commercial trucks and construction machinery', 'Active', '2025-10-14 06:37:53', '2025-10-24 13:02:05'),
(89, 'Oil Filter', '8-98092481-1', 'Oil Filters', 450.00, 'The Oil Filter 8-98092481-1 is designed to deliver superior engine protection and performance by efficiently trapping contaminants, sludge, and carbon deposits from engine oil. Built for durability and reliability, it ensures cleaner oil circulation and extends engine life even in demanding driving conditions.', 'uploads/68edf0519d89e_1760424017.jpeg', 'Type: Spin-on Oil Filter\r\nOuter Diameter: ~93 mm\r\nHeight: ~140 mm\r\nThread Size: M22 × 1.5\r\nBypass Valve Pressure: 1.2–1.6 bar\r\nMicron Rating: 25–30 µm\r\nMaterial: High-strength steel housing with synthetic blend media\r\nAnti-Drain Back Valve: Yes (Silicone)\r\nOperating Temperature: ?40°C to 150°C\r\nFiltration Efficiency: ? 98%\r\nCertification: ISO/TS 16949 / OEM Standard', 'Suitable for a wide range of Isuzu diesel engines and related heavy-duty models, including:\r\nIsuzu D-Max\r\nIsuzu NPR/NQR trucks\r\nIsuzu FRR/FSR series\r\nChevrolet Colorado (Diesel models)\r\nIndustrial and construction diesel machinery', 'Active', '2025-10-14 06:40:17', '2025-10-24 13:04:12'),
(90, 'Oil Filter', '9-0915-10001', 'Oil Filters', 110.00, 'The Oil Filter 9-0915-10001 provides dependable engine protection by efficiently removing impurities such as carbon, metal debris, and sludge from the oil system. Designed for high performance and durability, this filter ensures smooth oil flow and longer engine life for a wide range of vehicles.', 'uploads/68edf0db4502b_1760424155.jpeg', 'Type: Spin-on Oil Filter\r\nOuter Diameter: ~80 mm\r\nHeight: ~90 mm\r\nThread Size: M20 × 1.5\r\nBypass Valve Pressure: 1.0–1.3 bar\r\nMicron Rating: 25 µm\r\nMaterial: Steel shell with high-efficiency filter media\r\nAnti-Drain Back Valve: Yes (Rubber/Silicone)\r\nOperating Temperature: ?30°C to 120°C\r\nFiltration Efficiency: ? 98%\r\nCertifications: ISO/TS 16949 / OEM Standard', 'Toyota Corolla, Premio, and Allion models\r\nNissan Sunny and AD Van\r\nMitsubishi Lancer, Pajero Mini, and similar small-to-medium petrol engines\r\nLight commercial and passenger vehicles', 'Active', '2025-10-14 06:42:35', '2025-10-24 13:06:03'),
(91, 'Fuel Filter', 'B-B3Q-6744-BA', 'Fuel Filters', 350.00, 'The Fuel Filter BB3Q-6744-BA ensures optimal engine performance by removing dirt, water, and contaminants from fuel before it reaches the injectors. Engineered to meet or exceed OEM standards, this filter helps maintain fuel efficiency and prolong the life of your fuel system components.', 'uploads/68edf1d3e91d3_1760424403.jpeg', 'Type: Cartridge Fuel Filter\r\nOuter Diameter: ~88 mm\r\nHeight: ~105 mm\r\nMicron Rating: 10–15 µm\r\nFiltration Efficiency: ? 99%\r\nMaterial: Multi-layer cellulose and synthetic fiber\r\nCompatible Fuel Type: Diesel\r\nOperating Pressure: Up to 10 bar\r\nOperating Temperature: ?30°C to +120°C\r\nOEM Quality: Equivalent to original manufacturer standards\r\nCertifications: ISO 9001 / ISO/TS 16949', 'Ford Ranger (T6/PX)\r\nFord Everest\r\nMazda BT-50 (2011 onwards)\r\nDiesel engines with common rail injection systems', 'Active', '2025-10-14 06:46:43', '2025-10-26 08:01:23'),
(95, 'AIR FILTER', '8-98140265-0', 'Air Filters', 350.00, 'AIR FILTER', 'uploads/69c3ae6807a2f_1774431848.png', '', 'USED BY DMAX NEW MODEL', 'Active', '2026-03-25 09:44:08', '2026-03-25 09:44:08');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `code` (`code`),
  ADD KEY `idx_products_category` (`category`),
  ADD KEY `idx_products_status` (`status`),
  ADD KEY `idx_products_code` (`code`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=96;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
